# Generated by Django 4.0.10 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_company_cover_image_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
