# Generated by Django 4.0.10 on 2024-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_user_avatar_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
