# Generated by Django 4.0.10 on 2024-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='title',
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
