# Generated by Django 4.0.10 on 2024-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_remove_userexperience_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='start_date',
            field=models.DateField(),
        ),
    ]
