# Generated by Django 4.2.13 on 2024-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_alter_application_id_alter_bugreport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Reviewed'), (2, 'Rejected'), (3, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Interviewing'), (2, 'Closed')], default=0),
        ),
    ]
